// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentsService.Infrastructure.Persistence;

#nullable disable

namespace PaymentsService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608112806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentsService.Domain.Entities.Account", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("balance");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("caption");

                    b.HasKey("UserID");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PaymentsService.Domain.Entities.OrderToPayMessage", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Bill")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("bill");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Reserved")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("OrderID");

                    b.ToTable("order-to-pay-messages", (string)null);
                });

            modelBuilder.Entity("PaymentsService.Domain.Entities.PaidOrderMessage", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload");

                    b.Property<DateTime>("Reserved")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved");

                    b.HasKey("OrderID");

                    b.ToTable("paid-order-messages", (string)null);
                });

            modelBuilder.Entity("PaymentsService.Infrastructure.DTO.OrderIdDTO", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.ToTable("order-id-dto-type", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
